#!/bin/bash

# Copyright (C) 2011 9Apps.net
# 
# This file is part of 9Apps/MongoDB.
# 
# 9Apps/MongoDB is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# 9Apps/MongoDB is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with 9Apps/MongoDB. If not, see <http://www.gnu.org/licenses/>.

export EC2_KEY_DIR=/root/.ec2
export AWS_CREDENTIAL_FILE=${EC2_KEY_DIR}/aws_credentials.txt
export EC2_PRIVATE_KEY=${EC2_KEY_DIR}/pk-.pem
export EC2_CERT=${EC2_KEY_DIR}/cert-.pem
export EC2_ACCESS_KEY=''
export AWS_ACCESS_KEY_ID=''
export EC2_SECRET_KEY=''
export AWS_SECRET_ACCESS_KEY=''
export EC2_USER_ID=''
export EC2_REGION=''
export SDB_SERVICE_URL='https://sdb.amazonaws.com'
