#!/bin/bash
#
# install http://code.google.com/p/amazon-simpledb-cli/
# and http://developer.amazonwebservices.com/connect/entry.jspa?externalID=1136
# WARNING: make sure to install the required packages of the second as well

# first make sure we have enough information to do the work
source /root/config.sh

# only make backups when we are NOT master
if [ `/usr/bin/mongo --quiet --eval 'rs.isMaster().ismaster'` != 'false' ]; then
	echo 'master, no backups';
	exit;
fi

vol=`/usr/bin/ec2-describe-instance-attribute ${EC2_INSTANCE_ID} --block-device-mapping | /bin/grep "/dev/sdc" | /usr/bin/awk '{print $3}'`
if [ "${vol}" == "" ]; then
	echo "no volume, lets get outa here"
	exit
fi

# if called with a parameter that is accepted by 'date --date'
# it creates a date based on that value. if it is empty we take
# a default expiration of 24 hours
offset=$1
if [ "${offset}" == "" ]; then
    offset="24 hours"
fi

expiration=$(/bin/date -u --date="${offset}" +"%Y-%m-%d %H:%M:%S")
timestamp=$(/bin/date -u +"%Y-%m-%d %H:%M:%S")
if [ "$expiration" == "" ]; then
    exit 0
fi

mount="/var/mongodb"

/usr/bin/mongo --quiet admin /root/lock.js
/usr/sbin/xfs_freeze -f ${mount}
snapshot=($(/usr/bin/ec2-create-snapshot ${vol} --region ${EC2_REGION} --description "Backup of ${vol} - expires ${expiration}"))
/usr/sbin/xfs_freeze -u ${mount}
/usr/bin/mongo --quiet admin /root/unlock.js

# now add an item to the SimpleDB domain 
# containing the snapshot id and its expiration
/usr/local/bin/simpledb put ${SET_NAME} ${snapshot[1]} expires="${expiration}" timestamp="${timestamp}"
