#!/bin/bash
#
# install http://code.google.com/p/amazon-simpledb-cli/
# and http://developer.amazonwebservices.com/connect/entry.jspa?externalID=1136
# WARNING: make sure to install the required packages of the second as well

# first make sure we have enough information to do the work
source /root/config.sh

now=$(/bin/date +"%Y-%m-%d %H:%M:%S")

snapshots=$(/usr/local/bin/simpledb select "select * from ${SET_NAME} where expires < '${now}'")

for snapshot in $snapshots
do
    snap=`expr match "$snapshot" '.*\(snap-........\).*'`
    if [ -n "$snap" ]; then
        # remove the item from SimpleDB
        /usr/local/bin/simpledb delete ${SET_NAME} $snap
        # delete the snapshot itself
        /usr/bin/ec2-delete-snapshot $snap --region ${EC2_REGION}
    fi
done
