#!/bin/bash

apt-get install build-essential git-core

# see this install guide http://aws.amazon.com/articles/3998
apt-get install python-setuptools

# install boto
mkdir boto && cd boto
git clone https://github.com/boto/boto.git .
python setup.py install

# install monit and related scripts
apt-get install bison flex libssl-dev
wget http://mmonit.com/monit/dist/monit-5.2.tar.gz
tar xzvf monit-5.2.tar.gz 
cd monit-5.2

./configure
make
make install

# install mongodb
apt-get install unzip xfsprogs python-dev python-pip
pip install -U pymongo

echo "deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen" >> /etc/apt/sources.list
apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
apt-get update && apt-get install mongodb-10gen

stop mongodb
mkdir /var/mongodb

sed -i 's/\/var\/lib\/mongodb/\/var\/mongodb\/lib/' /etc/mongodb.conf
sed -i 's/\/var\/log\/mongodb/\/var\/mongodb\/log/' /etc/mongodb.conf
sed -i 's/--start/--rest --oplogSize 5120 --start --pidfile \/var\/run\/mongodb.pid/' /etc/init/mongodb.conf

sed -i 's/universe/multiverse/g' /etc/apt/sources.list
apt-get update
apt-get install ec2-api-tools

./create_mongodb_volume.sh

mkdir -p /var/mongodb/lib
mkdir -p /var/mongodb/log
chown -R mongodb.mongodb /var/mongodb
restart mongodb

# Installing AWS SDK for PHP
apt-get install libssl-dev php5-cli php-pear php5-curl php5-dev

pear channel-discover pear.amazonwebservices.com
pear install aws/sdk

# Installing PHP MongDB
pecl install mongo

echo "; configuration for php MongDB module
extension=mongo.so" > /etc/php5/cli/conf.d/mongo.conf
cat /etc/php5/cli/conf.d/mongo.conf >> /etc/php5/cli/php.ini
